# ─────────────────────────────────────────
# AGENT 4 — Report Generator Agent
# Job: Generate AI report using Gemini
# ─────────────────────────────────────────
def report_generator_agent(patient_info, scan_result, comparison=None):
    print(f"\n[Agent 4] 📝 Generating AI medical report...")

    try:
        from google import genai
        from config import GEMINI_API_KEY

        # Build the prompt for Gemini
        prompt = f"""
You are an expert neuro-radiologist AI assistant. 
Write a detailed medical report for the following brain tumor scan.

PATIENT INFORMATION:
- Patient ID : {patient_info['patient_id']}
- Name       : {patient_info['name']}
- Age        : {patient_info['age']}
- Gender     : {patient_info['gender']}

CURRENT SCAN RESULTS:
- Tumor Detected : {'Yes' if scan_result['tumor_detected'] else 'No'}
- Total Volume   : {scan_result['total_volume']} cm³
- NCR Volume     : {scan_result['ncr_volume']} cm³ ({scan_result['ncr_percent']}%)
- ED Volume      : {scan_result['ed_volume']} cm³ ({scan_result['ed_percent']}%)
- ET Volume      : {scan_result['et_volume']} cm³ ({scan_result['et_percent']}%)
"""

        # Add comparison data if this is a returning patient
        if comparison:
            prompt += f"""
COMPARISON WITH PREVIOUS SCAN ({comparison['previous_date']}):
- Previous Total Volume : {comparison['prev_total_volume']} cm³
- Total Change          : {comparison['total_change']['absolute']} cm³ ({comparison['total_change']['trend']})
- NCR Change            : {comparison['ncr_change']['absolute']} cm³ ({comparison['ncr_change']['trend']})
- ED Change             : {comparison['ed_change']['absolute']} cm³ ({comparison['ed_change']['trend']})
- ET Change             : {comparison['et_change']['absolute']} cm³ ({comparison['et_change']['trend']})
"""

        prompt += """
Please write a detailed medical report with these exact sections:

1. EXECUTIVE SUMMARY
2. DETAILED FINDINGS
3. COMPARISON WITH PREVIOUS SCAN (only if comparison data provided above)
4. CLINICAL OBSERVATIONS
5. RECOMMENDATIONS
6. DISCLAIMER (state this is AI-generated and must be reviewed by a physician)

Use professional medical language but keep it understandable.
"""

        # Call Gemini API
        print(f"[Agent 4] Calling Gemini API...")
        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt
        )

        report = response.text
        print(f"[Agent 4] ✅ Gemini report generated!")
        return report

    except Exception as e:
        print(f"[Agent 4] ⚠️ Gemini failed: {e}")
        print(f"[Agent 4] Using fallback report...")
        return _fallback_report(patient_info, scan_result, comparison)

# ─────────────────────────────────────────
# FALLBACK — Local report if Gemini fails
# ─────────────────────────────────────────
def _fallback_report(patient_info, scan_result, comparison=None):
    """Generate a basic report locally without Gemini"""

    report = f"""
1. EXECUTIVE SUMMARY
This report presents the findings of an AI-assisted brain MRI analysis 
for patient {patient_info['name']} (ID: {patient_info['patient_id']}).
{'A brain tumor was detected.' if scan_result['tumor_detected'] else 'No significant tumor was detected.'}

2. DETAILED FINDINGS
Total Tumor Volume : {scan_result['total_volume']} cm³
- NCR (Necrotic Core)     : {scan_result['ncr_volume']} cm³ ({scan_result['ncr_percent']}%)
- ED  (Edema)             : {scan_result['ed_volume']} cm³ ({scan_result['ed_percent']}%)
- ET  (Enhancing Tumor)   : {scan_result['et_volume']} cm³ ({scan_result['et_percent']}%)
"""

    if comparison:
        report += f"""
3. COMPARISON WITH PREVIOUS SCAN ({comparison['previous_date']})
- Previous Total Volume : {comparison['prev_total_volume']} cm³
- Current Total Volume  : {scan_result['total_volume']} cm³
- Change                : {comparison['total_change']['absolute']} cm³ ({comparison['total_change']['trend']})
- NCR Change            : {comparison['ncr_change']['absolute']} cm³ ({comparison['ncr_change']['trend']})
- ED  Change            : {comparison['ed_change']['absolute']} cm³ ({comparison['ed_change']['trend']})
- ET  Change            : {comparison['et_change']['absolute']} cm³ ({comparison['et_change']['trend']})
"""

    report += f"""
4. CLINICAL OBSERVATIONS
The AI model analyzed the provided MRI modalities (FLAIR, T1, T1CE, T2)
and segmented the tumor regions automatically.

5. RECOMMENDATIONS
Please consult a qualified neuro-radiologist or neurosurgeon 
for clinical decision making based on these findings.

6. DISCLAIMER
This report was generated by an AI system and must be reviewed 
and validated by a licensed physician before any clinical use.
"""
    return report
